# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include CurationConcerns::BasicMetadata
  class_attribute :do_index, default: true

  def self.do_index
     @@do_index ||= true
  end

  # Override method that does not currently scale to large collections, disabling size sorting of collections
  def bytes
    0
  end

  property :institution, predicate: ::RDF::Vocab::FOAF.based_near do |index|
    index.as :stored_searchable
  end

  property :pub_place, predicate: ::RDF::Vocab::DC.Location do |index|
    index.as :stored_searchable
  end

  # required
  property :file_name, predicate: ::RDF::Vocab::DC.MediaTypeOrExtent do |index|
    index.as :stored_searchable
  end

  # required
  property :name_code, predicate: ::RDF::Vocab::DC.identifier do |index|
    index.as :stored_searchable
  end

  # property :display_on_home, predicate: ::RDF::Vocab::DC.identifier, multiple: false do |index|
  #   index.as :stored_searchable
  # end

  def update_index
    CollectionIndexJob.perform_later(self.id) unless CollectionIndexJob.exists?(self.id)
  end

  protected
  def update_needs_index?
    Collection.do_index && ActiveFedora.enable_solr_updates?
  end
end
